import type { Metadata } from 'next';
import { setRequestLocale } from 'next-intl/server';
import { LegalPage } from '@/components/legal-page';
import { Link } from '@/i18n/navigation';
import { PLAN_MONTHLY_MINUTES, AUDIO_CONSTRAINTS } from '@audio-to-text/shared/types';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'The rules for using Audio→Text.',
};

const SUPPORT_EMAIL = 'support@audio-to-text.app';

export default async function TermsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <LegalPage title="Terms of Service" lastUpdated="July 2026">
      <p>These terms govern your use of Audio→Text. By creating an account, you agree to them.</p>

      <section>
        <h2>The service</h2>
        <p>
          Audio→Text lets you upload an audio file and receive a text transcript, generated by
          OpenAI&apos;s Whisper model. The free plan includes {PLAN_MONTHLY_MINUTES.free} minutes of
          audio per month; files must be under {AUDIO_CONSTRAINTS.MAX_FILE_SIZE_BYTES / 1024 / 1024}{' '}
          MB and in a supported format ({AUDIO_CONSTRAINTS.SUPPORTED_FORMATS.join(', ')}).
        </p>
      </section>

      <section>
        <h2>Acceptable use</h2>
        <p>You agree not to upload audio that:</p>
        <ul>
          <li>You don&apos;t have the right to record, possess, or share.</li>
          <li>Contains illegal content, or violates someone else&apos;s privacy or rights.</li>
          <li>You&apos;re uploading to abuse, overload, or probe the service&apos;s security.</li>
        </ul>
        <p>
          We may suspend or delete accounts that violate these terms, or that abuse the free
          plan&apos;s quota (for example, scripted mass uploads).
        </p>
      </section>

      <section>
        <h2>Accuracy</h2>
        <p>
          Transcripts are generated automatically and may contain errors — accents, background
          noise, audio quality, and ambiguous speech can all affect accuracy. Don&apos;t rely on a
          transcript for decisions where an error would matter (legal, medical, financial, or
          safety-critical contexts) without independently verifying it against the original audio.
        </p>
      </section>

      <section>
        <h2>No warranty, limited liability</h2>
        <p>
          The service is provided &quot;as is&quot;, without warranties of any kind. We are not
          liable for any damages arising from your use of the service, including inaccurate
          transcripts, service interruptions, or data loss, to the fullest extent permitted by law.
        </p>
      </section>

      <section>
        <h2>Your content</h2>
        <p>
          You retain all rights to the audio you upload and the transcripts you receive. We claim no
          ownership over either. See our <Link href="/privacy">Privacy Policy</Link> for exactly how
          your audio and transcripts are handled and stored.
        </p>
      </section>

      <section>
        <h2>Changes</h2>
        <p>
          We may update these terms as the service evolves. Continuing to use Audio→Text after a
          change means you accept the updated terms. Questions? Email {SUPPORT_EMAIL}.
        </p>
      </section>
    </LegalPage>
  );
}
